sudo: false
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"

os:
  - linux
  - osx

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

env:
  global:
    - CXX=g++-4.9
    - CC=gcc-4.9

install: npm install

script: travis_retry npm test
